repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        files: ^(src|tests)/
        exclude: ^\.venv/
        args: [
            '--select=E9',  # Only syntax errors for now
            '--max-line-length=100',
            '--ignore=D,E501,E203,W503,F'  # Ignore docstring, line length, and unused import issues
        ]
